# Sinusoidal Embedding

In [11]:
import math
import torch

from torch import nn

from src.model.embedding import Embedding

T = 10
n_embd = 4

pos = torch.arange(T).unsqueeze(1)
two_i = torch.arange(0, n_embd, 2)
div_term = torch.exp(-math.log(10000.0) * two_i / n_embd)
pos_embeddings = torch.zeros(T, n_embd)
pos_embeddings[:, 0::2] = torch.sin(pos * div_term)
pos_embeddings[:, 1::2] = torch.cos(pos * div_term)

print(pos_embeddings.numpy())

[[ 0.          1.          0.          1.        ]
 [ 0.84147096  0.54030234  0.00999983  0.99995   ]
 [ 0.9092974  -0.41614684  0.01999867  0.9998    ]
 [ 0.14112    -0.9899925   0.0299955   0.99955004]
 [-0.7568025  -0.6536436   0.03998933  0.9992001 ]
 [-0.9589243   0.2836622   0.04997917  0.99875027]
 [-0.2794155   0.96017027  0.059964    0.99820054]
 [ 0.6569866   0.75390226  0.06994285  0.997551  ]
 [ 0.98935825 -0.14550003  0.07991469  0.9968017 ]
 [ 0.4121185  -0.91113025  0.08987854  0.9959527 ]]
